---

- fail:
    msg: 'jekyll_rollout_instance variable has to be set with --extra-vars "jekyll_rollout_instance=project"'
  when: jekyll_rollout_instance == ''

- name: Include instance tasks
  include_tasks: instance.yml
  loop: "{{ jekyll_instances }}"
  loop_control:
    loop_var: instance
  when: >
    instance.name == jekyll_rollout_instance and
    (instance.state is undefined or instance.state == 'active')
  tags: jekyll
